lck/app.py
from flask import Flask, render_template, request, redirect, url_for, flash, session
from flask_cors import CORS
import time
import requests
from bs4 import BeautifulSoup
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()
DEBUG = True


def create_app():
    app = Flask(__name__)
    app.config.from_object(config)
    import schema
    app.secret_key = 'some_secret'
    CORS(app)
    from views import mainpage, teamrankpage, insertpage, t_match
    app.register_blueprint(mainpage.bp)
    app.register_blueprint(teamrankpage.bp)
    app.register_blueprint(insertpage.bp)
    app.register_blueprint(t_match.bp)
    return app


if __name__ == '__main__':
    app.run()

lck/views/insertpage.py
from flask import Blueprint, render_template, request
from app import db
import os
import sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from schema import lckmatch
bp = Blueprint('insert', __name__, url_prefix='/insert')

@bp.route('/')
def MainPage():
	return render_template('insertpage.html')

@bp.route('/create/', methods=('POST',))
def create():
    mdate = request.form['mdate']
    mtime = request.form['mtime']
    team1 = request.form['team1']
    team2 = request.form['team2']
    newmatch = lckmatch(mdate = mdate, mtime = mtime, team1 = team1, team2 = team2)
    db.session.add(newmatch)
    db.session.commit()
    return render_template('insertpage.html')

lck/views/mainpage.py
from flask import Blueprint, render_template

bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def MainPage():
    return render_template('index.html')

lck/views/t_match.py
from flask import Blueprint, Flask, render_template, request, redirect ,url_for, flash, session
from flask_cors import CORS
import pymysql
import time
from datetime import datetime

bp = Blueprint('t_match', __name__, url_prefix='/t_match')

@bp.route('/')
def t_match():
    tm = datetime.today().strftime('%Y%m%d')
    time = int(tm)
    db = pymysql.connect(host='localhost', user='root', passwd='1234', db='lck', charset='utf8')
    cur = db.cursor()

    sql = "select mdate,mtime,team1,team2 from lckmatch where mdate = '%s'"%(time)
    cur.execute(sql)
    data = cur.fetchall()
    db.commit()

    cur.close()
    db.close()
    print(data)

    

    return render_template('t_match.html',data = data)

lck/views/teamrankpage.py
from flask import Blueprint, render_template
import requests
from bs4 import BeautifulSoup
import pymysql

bp = Blueprint('teamrank', __name__, url_prefix='/rank')
viewRanking = 0  # 0: Team Ranking 1: POG Ranking


def getTeamRank():
    b = 1
    url = "https://namu.wiki/w/2021%20LoL%20Champions%20Korea%20Spring"

    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    rank = soup.select(
        '#app > div > div:nth-child(2) > article > div:nth-child(5) > div:nth-child(2) > div > div > div:nth-child(15) > div > table > tbody')
    t = []
    k = []
    r = []
    for x in rank:
        tr_tag = x.find_all('tr')
        for y in tr_tag:
            td_tag = y.find_all('td')
            for q in td_tag:
                div_tag = q.find_all('div')
                for s in div_tag:
                    digit = s.get_text()
                    t.append(digit)
    six = 0
    four = 3

    for i in range(11, 98):
        if(six == 6):
            four -= 1
            if(four > 0):
                continue
            else:
                r.append(k)
                k = []
                four = 3
                six = 0
        else:
            six += 1
            k.append(t[i])
            if(i == 97):
                r.append(k)

    for team in range(0, 10):
        r[team].append("../static/image/team/" + r[team][0] + ".png")

    return r


def getPOGRank():
    url = "https://namu.wiki/w/2021%20LoL%20Champions%20Korea%20Spring"
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')
    ranking = soup.select_one(
        "#app > div > div:nth-child(2) > article > div:nth-child(5) > div:nth-child(2) > div > div > div:nth-child(31) > div")
    pog_ranks = ranking.find_all('td')
    pog_data = []
    player = []
    p_cnt = 4

    for pog_rank in pog_ranks[7:]:
        pog_text = pog_rank.get_text()

        if '[' in pog_text[:5]:
            break
        if pog_text != '':
            player.append(pog_text)
            p_cnt -= 1

        if p_cnt == 0:
            pog_data.append(player)
            p_cnt = 4
            player = []

    for x in range(0, len(pog_data)):
        pname = pog_data[x][2]
        db = pymysql.connect(host='localhost', user='root', passwd='1234', db='lck', charset='utf8')
        cur = db.cursor()

        sql = "select liner from lckplayer where playername = '%s'"%(pname)
        cur.execute(sql)
        data = cur.fetchall()
        pog_data[x].append("../static/image/line/" + data[0][0] + ".png")
        # print("query : " , sql)
        # print(data[0][0])
        sql = "select team from lckplayer where playername = '%s'"%(pname)
        cur.execute(sql)
        data = cur.fetchall()
        pog_data[x].append("../static/image/team/" + data[0][0] + ".png")
        db.commit()
        cur.close()
        db.close()
    print(pog_data)
    return pog_data


r = getTeamRank()
pog_data = getPOGRank()

@bp.route('/team')
def onTeamRank():
    viewRanking = 0
    return render_template('rank.html', data_list=r, viewRanking=viewRanking)


@bp.route('/pog')
def onPOGRank():
    viewRanking = 1
    return render_template('rank.html', pog_data=pog_data, viewRanking=viewRanking)

lck/templates/index.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='slide.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" > </script>
	<script src="{{ url_for('static', filename='js/jquery.min.js') }}" > </script>
	<script src="{{ url_for('static', filename='js/slide.js') }}" > </script>
    <title>역시민균이다..</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-primary">
		<a class="navbar-brand" href="/" style="color:white; font-size: 28px;">LCK.GG</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
		  <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ml-5">
			<li class="nav-item dropdown" style="margin-right: 30px;">
				<a style="color:white" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					<span id="menumouseover">Ranking</span>
				</a>
				<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
					<li><a class="dropdown-item" href="/rank/team">Team Ranking</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="/rank/pog">MVP Ranking</a></li>
				  </ul>
			</li>

			<li class="nav-item">
				<a class="nav-link" href="/t_match" style="color: white;" id="menumouseover">Today's MatchUp</a>
			  </li>
		  </ul>
		</div>
	  </nav>
{% block content %}
{% endblock %}
</body>
</html>

lck/templates/insertpage.html
{% extends 'index.html' %}
{% block content %}
    <form action="{{ url_for('insert.create') }}" method="post">
        날짜
        <textarea name="mdate" id="mdate" cols="15"></textarea>
        <br>
        시간
        <textarea name="mtime" id="mtime" cols="15"></textarea>
        <br>
        팀1
        <textarea name="team1" id="team1" cols="15"></textarea>
        팀2
        <textarea name="team2" id="team2" cols="15"></textarea>

        <input type="submit" value="매치등록">
    </form>
{% endblock %}

lck/templates/rank.html
{% extends 'index.html' %}
{% block content %}
<body>
    {% if viewRanking == 0 %}
        <img src="../static/image/background/lckbanner.jpg" style="width:100%; height: 113px;">
        <table class="table" style="text-align: center; font-size:20px;">
            <caption style="text-align: center;">파란색: 4강 PO 진출 | 녹색: 6강 PO 진출 | 노란색: 포스트시즌 진출 실패 | 볼드체: 순위 확정</caption>
            <thead class="table-light" style="background-color: gainsboro;">
                <tr>
                    <th scope="col">순위</th>
                    <th scope="col">팀</th>
                    <th scope="col">승</th>
                    <th scope="col">패</th>
                    <th scope="col">세트 득실</th>
                    <th scope="col">득실차</th>
                    <th scope="col">연속</th>
                </tr>
            </thead>
            <tbody>
                <tr class="table-primary">
                    <th scope="row">1</th>
                    <td><img src= {{ data_list[0][6] }} id="teamimage">{{ data_list[0][0] }}</td>
                    <td>{{ data_list[0][1] }}</td>
                    <td>{{ data_list[0][2] }}</td>
                    <td>{{ data_list[0][3] }}</td>
                    <td>{{ data_list[0][4] }}</td>
                    <td>{{ data_list[0][5] }}</td>
                </tr>
                <tr class="table-primary">
                    <th scope="row">2</th>
                    <td><img src= {{ data_list[1][6] }} id="teamimage">{{ data_list[1][0] }}</td>
                    <td>{{ data_list[1][1] }}</td>
                    <td>{{ data_list[1][2] }}</td>
                    <td>{{ data_list[1][3] }}</td>
                    <td>{{ data_list[1][4] }}</td>
                    <td>{{ data_list[1][5] }}</td>
                </tr>
                <tr class="table-success">
                    <th scope="row">3</th>
                    <td><img src= {{ data_list[2][6] }} id="teamimage">{{ data_list[2][0] }}</td>
                    <td>{{ data_list[2][1] }}</td>
                    <td>{{ data_list[2][2] }}</td>
                    <td>{{ data_list[2][3] }}</td>
                    <td>{{ data_list[2][4] }}</td>
                    <td>{{ data_list[2][5] }}</td>
                </tr>
                <tr class="table-success">
                    <th scope="row">4</th>
                    <td><img src= {{ data_list[3][6] }} id="teamimage">{{ data_list[3][0] }}</td>
                    <td>{{ data_list[3][1] }}</td>
                    <td>{{ data_list[3][2] }}</td>
                    <td>{{ data_list[3][3] }}</td>
                    <td>{{ data_list[3][4] }}</td>
                    <td>{{ data_list[3][5] }}</td>
                </tr>
                <tr class="table-success">
                    <th scope="row">5</th>
                    <td><img src= {{ data_list[4][6] }} id="teamimage">{{ data_list[4][0] }}</td>
                    <td>{{ data_list[4][1] }}</td>
                    <td>{{ data_list[4][2] }}</td>
                    <td>{{ data_list[4][3] }}</td>
                    <td>{{ data_list[4][4] }}</td>
                    <td>{{ data_list[4][5] }}</td>
                </tr>
                <tr class="table-success">
                    <th scope="row">6</th>
                    <td><img src= {{ data_list[5][6] }} id="teamimage">{{ data_list[5][0] }}</td>
                    <td>{{ data_list[5][1] }}</td>
                    <td>{{ data_list[5][2] }}</td>
                    <td>{{ data_list[5][3] }}</td>
                    <td>{{ data_list[5][4] }}</td>
                    <td>{{ data_list[5][5] }}</td>
                </tr>
                <tr class="table-warning">
                    <th scope="row">7</th>
                    <td><img src= {{ data_list[6][6] }} id="teamimage">{{ data_list[6][0] }}</td>
                    <td>{{ data_list[6][1] }}</td>
                    <td>{{ data_list[6][2] }}</td>
                    <td>{{ data_list[6][3] }}</td>
                    <td>{{ data_list[6][4] }}</td>
                    <td>{{ data_list[6][5] }}</td>
                </tr>
                <tr class="table-warning">
                    <th scope="row">8</th>
                    <td><img src= {{ data_list[7][6] }} id="teamimage">{{ data_list[7][0] }}</td>
                    <td>{{ data_list[7][1] }}</td>
                    <td>{{ data_list[7][2] }}</td>
                    <td>{{ data_list[7][3] }}</td>
                    <td>{{ data_list[7][4] }}</td>
                    <td>{{ data_list[7][5] }}</td>
                </tr>
                <tr class="table-warning">
                    <th scope="row">9</th>
                    <td><img src= {{ data_list[8][6] }} id="teamimage">{{ data_list[8][0] }}</td>
                    <td>{{ data_list[8][1] }}</td>
                    <td>{{ data_list[8][2] }}</td>
                    <td>{{ data_list[8][3] }}</td>
                    <td>{{ data_list[8][4] }}</td>
                    <td>{{ data_list[8][5] }}</td>

                </tr>
                <tr class="table-warning">
                    <th scope="row">10</th>
                    <td><img src= {{ data_list[9][6] }} id="teamimage">{{ data_list[9][0] }}</td>
                    <td>{{ data_list[9][1] }}</td>
                    <td>{{ data_list[9][2] }}</td>
                    <td>{{ data_list[9][3] }}</td>
                    <td>{{ data_list[9][4] }}</td>
                    <td>{{ data_list[9][5] }}</td>
                </tr>
                
            </tbody>
        </table>
    {% else %}
    <img src="../static/image/background/lckpog.jpg" style="width:100%; height: 113px;">
    <table class="table" style="text-align: center; font-size:32px;">
        <thead class="table-primary">
            <tr>
                <th scope="col">순위</th>
                <th scope="col">선수명</th>
                <th scope="col">점수</th>
            </tr>
        </thead>
        <tbody>
            {% for player in pog_data %}
            <tr>
                {% if player[0] == "1" %}
                <th scope="row" style="background-color: azure;"><img src = "../static/image/decorate/crown.png" style="width: 40px;"></th>
                {% else %}
                <th scope="row" style="background-color: azure;">{{ player[0] }}</th>
                {% endif %}
                <td style="background-color:aliceblue;"><img src= {{ player[5] }} id="teamimage">{{ player[2] }}&nbsp;&nbsp;<img src= {{ player[4] }} id="teamimage"></td>
                <td style="background-color: azure;">{{ player[3] }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div style="background-color: black;">
        <img src="../static/image/decorate/challenger.png" class="imagecenter" style="height: 200px;">
    </div>
    {% endif %}
</body>
{% endblock %}

lck/templates/t_match.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}" > </script>
<script src="{{ url_for('static', filename='js/jquery.min.js') }}" > </script>
<style>
* {box-sizing: border-box}
body {font-family: Verdana, sans-serif; margin:0}
.mySlides {display: none;}
img {vertical-align: middle;}

/* Slideshow container */
.slideshow-container {
  max-width: 1730px;
  position: relative;
  margin: auto;
}

/* Next & previous buttons */
.prev, .next {
  cursor: pointer;
  position: absolute;
  top: 50%;
  width: auto;
  padding: 16px;
  margin-top: -22px;
  color: white;
  font-weight: bold;
  font-size: 18px;
  transition: 0.6s ease;
  border-radius: 0 3px 3px 0;
  user-select: none;
}

/* Position the "next button" to the right */
.next {
  right: 0;
  border-radius: 3px 0 0 3px;
}

/* On hover, add a black background color with a little bit see-through */
.prev:hover, .next:hover {
  background-color: rgba(0,0,0,0.8);
}

/* Caption text */
.text {
  color: #f2f2f2;
  font-size: 15px;
  padding: 8px 12px;
  position: absolute;
  bottom: 8px;
  width: 100%;
  text-align: center;
}

/* Number text (1/3 etc) */
.numbertext {
  color: #f2f2f2;
  font-size: 12px;
  padding: 8px 12px;
  position: absolute;
  top: 0;
}


/* Fading animation */
.fade {
  -webkit-animation-name: fade;
  -webkit-animation-duration: 1.5s;
  animation-name: fade;
  animation-duration: 1.5s;
  animation-fill-mode: forwards;
}

@-webkit-keyframes fade {
  from {opacity: 0.4} 
  to {opacity: 1.0}
}

@keyframes fade {
  from {opacity: 0.4} 
  to {opacity: 1.0}
}

/* On smaller screens, decrease text size */
@media only screen and (max-width: 300px) {
  .prev, .next,.text {font-size: 11px}
}
</style>
</head>
<body>
  <nav class="navbar navbar-expand-lg bg-primary">
		<a class="navbar-brand" href="/" style="color:white; font-size: 28px;">LCK.GG</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
		  <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ml-5">
			<li class="nav-item dropdown" style="margin-right: 30px;">
				<a style="color:white" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
					<span id="menumouseover">Ranking</span>
				</a>
				<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
					<li><a class="dropdown-item" href="/rank/team">Team Ranking</a></li>
					<li><hr class="dropdown-divider"></li>
					<li><a class="dropdown-item" href="/rank/pog">MVP Ranking</a></li>
				  </ul>
			</li>

			<li class="nav-item">
				<a class="nav-link" href="/t_match" style="color: white;" id="menumouseover">Today's MatchUp</a>
			  </li>
		  </ul>
		</div>
	  </nav>
    <!-- Slideshow container -->
    <div class="slideshow-container">

      <!-- Full-width images with number and caption text -->
      {% for i in data %}
          <div class="mySlides fade">
          <div class="numbertext">{{ loop.index }}/ 2</div>
          <img src="../static/image/match/match{{ loop.index }}_{{ i[2] }}{{ i[3] }}.jpg" id="match_teamimage">
          </div>
      {% endfor %}
  
      <!-- Next and previous buttons -->
      <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
      <a class="next" onclick="plusSlides(1)">&#10095;</a>
  </div>
  <br>

<script>
var slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
  // checkSlides();
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}


function showSlides(n) {
  // console.log("showSlides : " + n);
  var i;
  var slides = document.getElementsByClassName("mySlides");
  if (n > slides.length) {slideIndex = 1}    
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
      slides[i].style.display = "none";  
  }
  slides[slideIndex-1].style.display = "block";  
}
</script>

</body>
</html> 